import type { Metadata } from "next";

import clsx from "clsx";
import "./globals.css";



export const metadata: Metadata = {
  title: "Amakhoe Kars Portifolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx("antialiased")}>{children}</body>
    </html>
  );
}
